### ISSUE TITLE
Why does DistillationLoss use dot instead of kldiv?

### ISSUE THREAD

**Issue by wnma3mz** [Piyush-555/GaussianDistillation#1]
Great job
But I have a small question here, for distillation losses, why not use kl dispersion but multiplication!

https://github.com/Piyush-555/GaussianDistillation/blob/974b9504b25c04392a9f270e40f80cbf11a8e486/utils/misc.py#L35-L44

My idea like that,

```python
return nn.KLDivLoss(reduction="batchmean")(student, teacher) * (self.T ** 2)
```

**Comment by Piyush-555** [comment]
The loss implemented is actually a cross-entropy loss. Since cross-entropy and KL divergence are the same optimization-wise, anyone would be acceptable to use.

**Comment by wnma3mz** [comment]
Thanks for your reply. In my reproducing results, I found that using kl divergence would lead to slightly higher results. It's about two points. (`python distill_gaussian.py CIFAR10 200 200 --compare True --model_student resnet18`)

```python
return nn.KLDivLoss(reduction="batchmean")(student, teacher) * (self.T ** 2)
```

And finally, great work, inspired me.

**Comment by Piyush-555** [comment]
I might need to check that then. But thanks for the info!
